Update debtoo-install

diff --git a/debtoo-install b/debtoo-install
--- a/debtoo-install
+++ b/debtoo-install
@@ -1,8 +1,8 @@
 #!/bin/bash
-# debtoo-install v1.0.5 by Nathaniel Greenwell (NTVMB)
+# debtoo-install v1.1.0-testing by Nathaniel Greenwell (NTVMB)
 # This tool is not intended to install other distros, whether Debian-based or not.
 # Dependencies: bash, coreutils, util-linux, parted, iputils-ping, debootstrap, e2fsprogs, arch-install-scripts, gawk, grub2, dosfstools, efibootmgr
-VERSION=1.0.5
+VERSION=1.1.0-testing
 TARGET_DIR=/mnt/debtoo
 # Check for root access
 if [ $EUID -ne 0 ]; then
@@ -307,6 +307,7 @@ case $EXEC in
 esac
 
 # The fun part - the installation
+. /etc/os-release
 unset TARGET_DISK_NAME
 echo "Mounting partitions..."
 mkdir $TARGET_DIR
@@ -330,7 +331,22 @@ if [ $? -ne 0 ]; then
 	echo "Continuing without swap... (this may result in running out of memory)"
 fi
 echo "Installing the base system..."
-debootstrap --variant=minbase --no-merged-usr --include=grub2,dhcpcd5,iwd,man-db,texinfo,efibootmgr,zstd,tasksel,manpages,wget,curl,nano,vim,locales,build-essential ceres $TARGET_DIR
+case $VERSION_ID in
+	1)
+		CODENAME=chimaera
+		;;
+	2)
+		CODENAME=daedalus
+		;;
+	"unstable")
+		CODENAME=ceres
+		;;
+	*)
+		echo "Fatal: Cannot determine release."
+		exit 1
+		;;
+esac
+debootstrap --variant=minbase --no-merged-usr --include=grub2,dhcpcd5,iwd,man-db,texinfo,efibootmgr,zstd,tasksel,manpages,wget,curl,nano,vim,locales,build-essential $CODENAME $TARGET_DIR
 if [ $? -ne 0 ]; then
 	echo "Fatal: Failed to install the base system."
 	exit 1
